### ISSUE TITLE
Runtime error when starting extension

### ISSUE THREAD

**Issue by msorens** [bwateratmsft/memento-explorer#14]
I instrumented my extension to return an object conforming to the `IMementoExplorerExtension` interface as your directions indicate. When I run Memento Explorer I am able to pick my extension from the picker, but as soon as I do I get this error:
```
cannot open memento://styra.vscode-styra/workspace. Detail: Unable to read file 'memento://styra.vscode-styra/workspace' (TypeError: Cannot read properties of undefined (reading 'length'))
```

VSCode version 1.74.3

Any suggestions?

P.S. I enjoyed your privacy policy link. 😉

**Comment by bwateratmsft** [comment]
It's probably this line right here:
https://github.com/bwateratmsft/memento-explorer/blob/8420bb7d099760b0160b2d3d148f983d52219f5c/src/MementoFileSystemProvider.ts#L17

It seems the memento object has a nullish `_value`. I haven't tested but that may be what occurs when no values have been put into the memento yet.

**Comment by bwateratmsft** [comment]
Oh, it is the latter. This is due to [VSCode's new property mangling thing](https://code.visualstudio.com/updates/v1_74#_name-mangling-of-properties-and-method). I'll have to find out if it's deterministic...

**Comment by msorens** [comment]
Yeah, I looked as far as searching for `length` in your code and found the line you mentioned, but did not dig further. Thanks for checking so promptly...

**Comment by bwateratmsft** [comment]
@msorens I just updated the extension on the marketplace to 0.1.4. It should fix the issue at least for now, but a better long term solution will be needed eventually (#17).

**Comment by msorens** [comment]
0.1.4 works great; thank you!
And double thanks for a small but incredibly useful and easy to use extension. 🎉

**Comment by bwateratmsft** [comment]
Thanks! Honestly I made it mostly for myself for use on the Docker extension, but I figured I'd release it too :smile:
